name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      max-parallel: 1  
      matrix:
        python-version: [3.11]  # Стартираме само с Python 3.11

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies (disabled for debugging)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: "no-cache"
          restore-keys: |
            "no-cache"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Инсталираме flake8 за linting

      - name: Check for unapplied migrations
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Run Tests (if any)
        run: |
          python manage.py test || echo "No tests found, skipping."
